loggging:
  level:
    org.springframework.security: debug
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirectUri: http://localhost:4200/callback